export class Interview {
    /// <summary>
    /// 扫描的面访二维码Id
    /// </summary>
    InterviewQRCodeId: number;
    /// <summary>
    /// 扫码人的微信OpenId
    /// </summary>
    WxOpenId: string;
    /// <summary>
    /// 经度
    /// </summary>
    Longitude: number;
    /// <summary>
    /// 纬度
    /// </summary>
    Latitude: number;
    /// <summary>
    /// 被面访人姓名
    /// </summary>
    PersonName: string;
    /// <summary>
    /// 性别。0:男.1:女
    /// </summary>
    Gender: number;
    /// <summary>
    /// 手机号码
    /// </summary>
    Phone: string;
    /// <summary>
    /// 被面访人填写资料时用到的短信验证码
    /// </summary>
    VerificationCode: string;
    /// <summary>
    /// 评分星星数
    /// </summary>
    Stars: number;
    /// <summary>
    /// 评价标签，多个逗号分隔
    /// </summary>
    Tags: string;
    /// <summary>
    /// 评价
    /// </summary>
    Remark: string;
}